auth_key: d3457d16-19ca-57f8-84e0-36ef9b161279
server:
  address:
  port: 8080
database:
  model_type: mysql
  address: localhost
  port: 3306
  database: apiadmin
  username: root
  password: zhou1995
redis_cache:
  address: localhost
  password:
  port: 6379
  db: 0
  expire_time: 3600