http:
  addr: ":8080"
postgres:
  dsn: "postgres://admin:zhou123456@192.168.5.130:5432/apiadmin?sslmode=disable"
  max_open: 50
  max_idle: 10
  auto_migrate: true
redis:
  addr: "192.168.3.230:6379"
  password: ""
  db: 0
  jti_prefix: "jwt:jti:"
kafka:
  brokers: ["192.168.5.130:9092"]
  op_log_topic: "admin_op_log"
etcd:
  endpoints: ["192.168.5.130:2379"]
  ttl: 15
jwt:
  secret: "kdljfljffjghieutgjfjkfg8873274923847nfkfsbfryfy78fw84"
  expire_seconds: 7200
  issuer: "GOAPIAdmin"
log:
  level: "debug"
  format: "json"
app_meta:
  name: "GOAPIAdmin"
  version: "1.0"
wiki:
  online_time_seconds: 86400
upload:
  max_size_mb: 10
  allowed_ext: ["jpg","jpeg","png","gif","pdf","txt","zip","json"]
otel:
  enable: false
  endpoint: "localhost:4317"
  insecure: true
  sampler_ratio: 1.0
